### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sec13b** [BoomBookTR/AnyDesk-ID-License-Warning-Reset#1]
After i run the bat scripts .

![image](https://github.com/user-attachments/assets/b5f9dff4-3509-4075-b092-3b25e8c9dde7)

**Comment by BoomBookTR** [comment]
Komut dosyası çalışırken bir hata veriyor mu? Ayrıca dönüt olarak komut satırının ikisini de denediniz mi? Son olarak manuel olarak sağ tıklayıp yönetici olarak çalıştırıp bilgi verir misiniz?

**Comment by BoomBookTR** [comment]
Any error in batch script?
Did you try another batch file?
Finally did you try run as administrator?
